Algoritmo "tabuada"

Var
num,mult,i:inteiro


Inicio
Escreva("Digite um número ")
leia(num)
para i de 0 ate 10 passo 1 faca //vai fazer de 0 até 10 números, 1 por 1
mult<- num*i
escrevaL(num, " X", i , " =", mult)

fimpara


//poderia ser dessa maneira, de modo mais simples:
// Escreva("Digite um número ")
//leia(num)
//para i de 0 ate 10 passo 1 faca  - vai fazer de 0 até 10 números, 1 por 1
//escrevaL(num, " X", i , " =", mult)
//fimpara



Fimalgoritmo